### PR TITLE
fix hash large rars

### PR DESCRIPTION
**Pull request by ondrejbima**

### CODE REVIEW

**Comment by amet** [comment]
thx, have you tested this?

**Comment by ondrejbima** [comment]
a little, i have some rar archives with large file flag, but there are only ~180MB file in there.
not tested against real 2GB+ files.

**Comment by amet** [comment]
were you seeing any issues with those files before that required this fix? this is a straight copy/paste from opensubtitles dev page, i'd check on their forums as well.

http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes

**Comment by ondrejbima** [comment]
yep, there is i a typo problem.. method unpack is not defined

**Comment by amet** [comment]
ok, thx!

**Pull request merged**
