### PR TITLE
add slash or backslash at the end of path

### PR DESCRIPTION
**Pull request by ondrejbima**
fix xbmcvfs.exists in Helix
http://mirrors.xbmc.org/docs/python-docs/14.x-helix/xbmcvfs.html#-exists

### CODE REVIEW

**Comment by amet** [comment]
why was this broken in Helix? should it not be fixed there?

**Comment by ondrejbima** [comment]
In documentation for Gotham and Helix is "folder must end with slash or backslash".
In Helix method xbmcvfs.exists was "fix" and require slash at the end of path.
With missing slash return false event if folder exists.

**Comment by amet** [comment]
Does Gotham still work with your fix?

**Comment by ondrejbima** [comment]
yes, it works in Gotham
Dne 26. 10. 2014 4:58 "Zeljko Ametovic" notifications@github.com
napsal(a):

**Pull request merged**
