### PR TITLE
Add login to OpenSubtitles as a setting.

### PR DESCRIPTION
**Pull request by laric**
Adding login option to Opensubitle addon the same way as in the podnapisi addon.

### CODE REVIEW

**Comment by laric** [comment]
@amet  any chance of you adding this so we can have login option in the opensubtitles as well?

**Comment by amet** [comment]
sure, what do we gain with this?

**Comment by laric** [comment]
People who have accounts on opensubtitles.org can login and thus be allowed to download more subtitles per 24h period than the anonymous user who is limited in number of downloads per day.

**Comment by amet** [comment]
no complaints, just wasn't sure what the advantages were. thx!

**Pull request merged**
